import type { Product } from '@/entities/product/model/types'
import { ProductAvailability } from '@/entities/product/model/types'

export const products: Product[] = [
  {
    id: '1',
    title: 'Apple iPad Pro 11" (M4) 256 ГБ Space Black',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-pro-glass-select-gallery-2-202405?wid=5120&hei=2880&fmt=webp&qlt=90&.v=QU8rTGFZUkxWbm1Fc0VaUXQ2QVNpR0pvMjZnN3E5aGRZVXJIWmhFMitJSU9WV3R2ZHdZMXRzTjZIcWdMTlg4eUJQYkhSV3V1dC9oa0s5K3lqMGtUaGVKZVh6REdCb3NhUkU0K1Z6WFRtbCtXQm92T1BGMVFqb0UvQ214cjlZaHg&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-pro-glass-select-gallery-1-202405?wid=5120&hei=2880&fmt=webp&qlt=90&.v=QU8rTGFZUkxWbm1Fc0VaUXQ2QVNpSU5sSFgwakNWNmlhZ2d5NGpHdllWY09WV3R2ZHdZMXRzTjZIcWdMTlg4eUJQYkhSV3V1dC9oa0s5K3lqMGtUaGVKZVh6REdCb3NhUkU0K1Z6WFRtbC8yVWVIMmtHOUR3d3VRcTdXQWpyckQ&traceId=1',
    ],
    soldCount: 124,
    rating: { score: 4.7, reviewsCount: 38 },
    price: { current: 99990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPad',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '11"' },
          { name: 'Тип', value: 'Ultra Retina XDR (Tandem OLED)' },
          { name: 'Разрешение', value: '2420 × 1668 пикс.' },
          { name: 'Плотность пикселей', value: '264 пикс/дюйм' },
          { name: 'Частота обновления', value: '120 Гц (ProMotion)' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Покрытие', value: 'Антибликовое' },
          { name: 'Яркость', value: '1000 нит (HDR), 1600 нит (HDR-контент)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple M4' },
          { name: 'Ядра CPU', value: '9 (3 производительных + 6 энергоэффективных)' },
          { name: 'Ядра GPU', value: '10' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '8 ГБ' },
          { name: 'Накопитель', value: '256 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '12 МП (широкоугольная), ƒ/1.8' },
          { name: 'Видео', value: '4K, ProRes' },
          { name: 'Фронтальная', value: '12 МП Ultra Wide, Center Stage' },
        ],
      },
      {
        groupName: 'Apple Pencil и клавиатура',
        specs: [
          { name: 'Apple Pencil Pro', value: 'Поддержка' },
          { name: 'Apple Pencil (USB-C)', value: 'Поддержка' },
          { name: 'Magic Keyboard', value: 'Поддержка' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '31,29 Вт·ч' },
          { name: 'Автономность', value: 'до 10 ч (веб-сёрфинг)' },
          { name: 'Зарядка', value: 'USB-C (Thunderbolt / USB 4)' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Space Black' },
          { name: 'Материал корпуса', value: '100% переработанный алюминий' },
          { name: 'Безопасность', value: 'Face ID' },
          { name: 'ОС', value: 'iPadOS 18' },
          { name: 'Размеры', value: '249.7 × 177.5 × 5.3 мм' },
          { name: 'Вес', value: '444 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '2',
    title: 'Apple iPad Pro 13" (M4) 256 ГБ Space Black',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-pro-finish-select-202405-13inch-spaceblack_AV2?wid=5120&hei=2880&fmt=webp&qlt=90&.v=YXpaUEtKWGhlNnNrVGZkTEo4T0xsNDByMHhIZkdBbFEwRFROUE9ubkFjTVo4dzFhbDVTUTBkeWlEYVIzdWtXTzVwZk1WSFgzNmhFZllMYTFHb1ZRM3hNQnJMcnc4RkxJd3ZMc3hKZVVFWHNTR3c5UGxBQklhMGd1dFJQdmJvYmJtWmRIN3hydnVpcUZFTDQ4czVZOEpB&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-pro-finish-select-202405-13inch-spaceblack_AV1?wid=5120&hei=2880&fmt=webp&qlt=90&.v=YXpaUEtKWGhlNnNrVGZkTEo4T0xsNDByMHhIZkdBbFEwRFROUE9ubkFjTVo4dzFhbDVTUTBkeWlEYVIzdWtXT29vWDJoZ1VTdjZaMjhaK1h5ckJ1T2hNQnJMcnc4RkxJd3ZMc3hKZVVFWHVmRVFRMjFZOFY3cEkrWGZlYmZKdXQzY0NKa3ZTME9vSkRvZFVhUTRRNU1n&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-pro-finish-select-202405-13inch-spaceblack?wid=5120&hei=2880&fmt=webp&qlt=90&.v=YXpaUEtKWGhlNnNrVGZkTEo4T0xsNDByMHhIZkdBbFEwRFROUE9ubkFjT0FkTVhEZDlmdGh2cFlYWEZ5TmhXMlpGQnBBWVp4a3ZSd0Y4NzlDUVE4dUoyTGQvczVjTzVnd1B6UVQwaE1kY2ltdVdwbG5WMFRSbXYxQVhPWGZnNzlPSWh1UVhJRldSUVRIMWxicWhmRG1R&traceId=1',
    ],
    soldCount: 87,
    rating: { score: 4.8, reviewsCount: 24 },
    price: { current: 129990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPad',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '13"' },
          { name: 'Тип', value: 'Ultra Retina XDR (Tandem OLED)' },
          { name: 'Разрешение', value: '2752 × 2064 пикс.' },
          { name: 'Плотность пикселей', value: '264 пикс/дюйм' },
          { name: 'Частота обновления', value: '120 Гц (ProMotion)' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Покрытие', value: 'Антибликовое' },
          { name: 'Яркость', value: '1000 нит (HDR), 1600 нит (HDR-контент)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple M4' },
          { name: 'Ядра CPU', value: '9 (3 производительных + 6 энергоэффективных)' },
          { name: 'Ядра GPU', value: '10' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '8 ГБ' },
          { name: 'Накопитель', value: '256 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '12 МП (широкоугольная), ƒ/1.8' },
          { name: 'Видео', value: '4K, ProRes' },
          { name: 'Фронтальная', value: '12 МП Ultra Wide, Center Stage' },
        ],
      },
      {
        groupName: 'Apple Pencil и клавиатура',
        specs: [
          { name: 'Apple Pencil Pro', value: 'Поддержка' },
          { name: 'Apple Pencil (USB-C)', value: 'Поддержка' },
          { name: 'Magic Keyboard', value: 'Поддержка' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '38,99 Вт·ч' },
          { name: 'Автономность', value: 'до 10 ч (веб-сёрфинг)' },
          { name: 'Зарядка', value: 'USB-C (Thunderbolt / USB 4)' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Space Black' },
          { name: 'Материал корпуса', value: '100% переработанный алюминий' },
          { name: 'Безопасность', value: 'Face ID' },
          { name: 'ОС', value: 'iPadOS 18' },
          { name: 'Размеры', value: '286.6 × 214.9 × 5.1 мм' },
          { name: 'Вес', value: '579 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '3',
    title: 'Apple iPhone 16 128 ГБ Teal',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal_AV3?wid=5120&hei=2880&fmt=webp&qlt=90&.v=UXp1U3VDY3IyR1hNdHZwdFdOLzg1V0tFK1lhSCtYSGRqMUdhR284NTN4OFBjdm1iTDVHUUIydzA3NnRqc3JwS1pGQnBBWVp4a3ZSd0Y4NzlDUVE4dUoyTGQvczVjTzVnd1B6UVQwaE1kY2lsQUl3bUplV0NnaUJoa0N0NXhoVm9NUjhodU9MTHNlVnVUMUtlUmw4RU9R&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal_AV2?wid=5120&hei=2880&fmt=webp&qlt=90&.v=UXp1U3VDY3IyR1hNdHZwdFdOLzg1V0tFK1lhSCtYSGRqMUdhR284NTN4ODlFQXprM0hDbGN6dXdCdHZYOEllaVpGQnBBWVp4a3ZSd0Y4NzlDUVE4dUoyTGQvczVjTzVnd1B6UVQwaE1kY2g3WkQ0K3d6enlib0RFNk51VnJ3NGkwZWlkTmYwaG1taWdvU3JZRHlDL0tB&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal_AV1?wid=5120&hei=2880&fmt=webp&qlt=90&.v=UXp1U3VDY3IyR1hNdHZwdFdOLzg1V0tFK1lhSCtYSGRqMUdhR284NTN4K05tOGV2bzRuYjBHQm9BRXF6V0NIa1pGQnBBWVp4a3ZSd0Y4NzlDUVE4dUoyTGQvczVjTzVnd1B6UVQwaE1kY2djb0pRV1BLWkpwS3lTdmpyVm9XVnRXVi9BOUVIMG00R2gwMHk0cXVORTFB&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal?wid=5120&hei=2880&fmt=webp&qlt=90&.v=UXp1U3VDY3IyR1hNdHZwdFdOLzg1V0tFK1lhSCtYSGRqMUdhR284NTN4L29KblRMQzVUOE4vMXpkMWtFcm9GcXF2TWlpSzUzejRCZGt2SjJUNGl1VEE4bm1RcmlWRWp2eDN1WHNkSjNmUlpaWWVaY3B6VTFTdVNEWDF2OTRBYlY&traceId=1',
    ],
    soldCount: 580,
    rating: { score: 4.5, reviewsCount: 142 },
    price: { current: 79990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPhone',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '6.1"' },
          { name: 'Тип', value: 'Super Retina XDR OLED' },
          { name: 'Разрешение', value: '2556 × 1179 пикс.' },
          { name: 'Плотность пикселей', value: '460 пикс/дюйм' },
          { name: 'Частота обновления', value: '60 Гц' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Dynamic Island', value: 'Да' },
          { name: 'Яркость', value: '1000 нит (典型), 1600 нит (HDR), 2000 нит (наружная)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A18' },
          { name: 'Ядра CPU', value: '6 (2 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '5' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '8 ГБ' },
          { name: 'Накопитель', value: '128 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '48 МП Fusion, ƒ/1.6' },
          { name: 'Сверхширокоугольная', value: '12 МП, ƒ/2.2' },
          { name: 'Видео', value: '4K 60 кадр/с, Dolby Vision' },
          { name: 'Оптический зум', value: '0.5×, 1×, 2×' },
          { name: 'Фронтальная', value: '12 МП TrueDepth, ƒ/1.9' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '3 561 мАч' },
          { name: 'Автономность', value: 'до 22 ч (воспроизведение видео)' },
          { name: 'Быстрая зарядка', value: 'до 50% за 35 мин (адаптер 20 Вт)' },
          { name: 'Беспроводная зарядка', value: 'MagSafe 25 Вт, Qi2 15 Вт' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Teal' },
          { name: 'Материал корпуса', value: 'Алюминий' },
          { name: 'Безопасность', value: 'Face ID' },
          { name: 'ОС', value: 'iOS 18' },
          { name: 'Степень защиты', value: 'IP68' },
          { name: 'Action Button', value: 'Да' },
          { name: 'Camera Control', value: 'Да' },
          { name: 'Размеры', value: '147.6 × 71.6 × 7.8 мм' },
          { name: 'Вес', value: '170 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '4',
    title: 'Apple iPhone 16 Pro Max 1 ТБ Desert Titanium',
    images: [
      'https://istoreapple.ru/image/cache/catalog/ASYA/16PRO/iphone-16-pro-Desert-Titanium-1-702x702.jpg',
      'https://istoreapple.ru/image/cache/catalog/ASYA/16PRO/iphone-16-pro-Desert-Titanium-2-702x702.jpg',
      'https://istoreapple.ru/image/cache/catalog/ASYA/16PRO/iphone-16-pro-Desert-Titanium-3-702x702.jpg',
    ],
    soldCount: 203,
    rating: { score: 4.7, reviewsCount: 56 },
    price: { current: 179990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPhone',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '6.9"' },
          { name: 'Тип', value: 'Super Retina XDR OLED' },
          { name: 'Разрешение', value: '2868 × 1320 пикс.' },
          { name: 'Плотность пикселей', value: '460 пикс/дюйм' },
          { name: 'Частота обновления', value: '120 Гц (ProMotion)' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Always-On дисплей', value: 'Да' },
          { name: 'Dynamic Island', value: 'Да' },
          { name: 'Яркость', value: '1000 нит (典型), 1600 нит (HDR), 2000 нит (наружная)' },
          { name: 'Защитное стекло', value: 'Ceramic Shield (поколение 2)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A18 Pro' },
          { name: 'Ядра CPU', value: '6 (2 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '6' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '8 ГБ' },
          { name: 'Накопитель', value: '1 ТБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '48 МП (широкоугольная), ƒ/1.78' },
          { name: 'Сверхширокоугольная', value: '48 МП, ƒ/2.2' },
          { name: 'Телефото', value: '12 МП, 5× оптический зум, ƒ/2.8' },
          { name: 'Видео', value: '4K 120 кадр/с, Dolby Vision, ProRes' },
          { name: 'Оптический зум', value: '0.5×, 1×, 2×, 5×' },
          { name: 'Фронтальная', value: '12 МП TrueDepth, ƒ/1.9' },
          { name: 'Camera Control', value: 'Да' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '4 685 мАч' },
          { name: 'Тип', value: 'Li-Ion' },
          { name: 'Автономность', value: 'до 33 ч (воспроизведение видео)' },
          { name: 'Быстрая зарядка', value: 'до 50% за 35 мин (адаптер 20 Вт)' },
          { name: 'Беспроводная зарядка', value: 'MagSafe 25 Вт, Qi2 15 Вт' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Desert Titanium' },
          { name: 'Материал корпуса', value: 'Титан класса 5' },
          { name: 'Безопасность', value: 'Face ID' },
          { name: 'ОС', value: 'iOS 18' },
          { name: 'Степень защиты', value: 'IP68' },
          { name: 'Action Button', value: 'Да' },
          { name: 'Размеры', value: '163.0 × 77.6 × 8.25 мм' },
          { name: 'Вес', value: '227 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '5',
    title: 'Apple Watch Series 10 42 мм Silver',
    images: [
      'https://istoreapple.ru/image/cache/catalog/!AOL/watch/ser%2010/sport%20band/fk1q3rvgfvjxunoigz750bxy74iemlwg-702x702.jpg',
      'https://istoreapple.ru/image/cache/catalog/!AOL/watch/ser%2010/sport%20band/6for4yae4742xfbjvjfitlyhp9nbpvpt-702x702.jpg',
    ],
    soldCount: 95,
    rating: { score: 4.8, reviewsCount: 31 },
    price: { current: 44990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'Apple Watch',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Дисплей',
        specs: [
          { name: 'Диагональ', value: '42 мм' },
          { name: 'Тип', value: 'OLED (LTPO) Always-On Retina' },
          { name: 'Разрешение', value: '396 × 484 пикс.' },
          { name: 'Яркость', value: 'до 2000 нит' },
          { name: 'Защитное стекло', value: 'Ion-X (стекло)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple S10 SiP' },
          { name: 'Ядра CPU', value: '2' },
          { name: 'Чип связи', value: 'W2' },
          { name: 'Вместимость', value: '64 ГБ' },
        ],
      },
      {
        groupName: 'Датчики',
        specs: [
          { name: 'Пульс', value: 'Оптический датчик сердечного ритма (3-е поколение)' },
          { name: 'ЭКГ', value: 'Электрический датчик сердечной активности' },
          { name: 'Температура', value: 'Датчик температуры (запястье)' },
          { name: 'Кислород', value: 'Пульсоксиметр (SpO2)' },
          { name: 'Высотомер', value: 'Always-on' },
          { name: 'Глубиномер', value: 'Да' },
          { name: 'Компас', value: 'Встроенный' },
          { name: 'Акселерометр', value: 'Да' },
          { name: 'Гироскоп', value: 'Да' },
          { name: 'Датчик освещённости', value: 'Да' },
          { name: 'Обнаружение падения', value: 'Да' },
          { name: 'Экстренный вызов SOS', value: 'Да' },
          { name: 'Стадии сна', value: 'Да' },
          { name: 'Управление жестами', value: 'Да' },
        ],
      },
      {
        groupName: 'Связь',
        specs: [
          { name: 'GPS', value: 'GPS, GLONASS, Galileo, BeiDou, QZSS' },
          { name: 'Wi-Fi', value: '802.11b/g/n 2.4 ГГц и 5 ГГц' },
          { name: 'Bluetooth', value: '5.3' },
          { name: 'NFC', value: 'Да (Apple Pay)' },
          { name: 'LTE', value: 'GPS + Cellular' },
        ],
      },
      {
        groupName: 'Аккумулятор',
        specs: [
          { name: 'Автономность', value: 'до 18 ч (обычный режим)' },
          { name: 'Быстрая зарядка', value: '80% за 45 мин' },
          { name: 'Зарядка', value: 'Магнитная USB-C зарядка' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Silver' },
          { name: 'Материал корпуса', value: 'Алюминий' },
          { name: 'Материал ремешка', value: 'Sport Band (M/L 140-245 мм)' },
          { name: 'Водозащита', value: 'WR100 (100 м)' },
          { name: 'ОС', value: 'watchOS 11' },
          { name: 'Размеры', value: '42 × 36 × 9.7 мм' },
          { name: 'Вес', value: '36.4 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '6',
    title: 'Apple AirPods 4',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-4-select-202409_FV1?wid=976&hei=916&fmt=jpeg&qlt=90&.v=WnVKRVRUTFVsYThXaWkydWViL1Q3ZDZGTE9TV3RDcGJJclBqdUtzdTJYYjNHc3NlSmU2dzJyR1kxZEwyTE1neUJkRlpCNVhYU3AwTldRQldlSnpRa0NZZXAxWFNjRXhITDI1RVE5YVpyU0E',
    ],
    soldCount: 420,
    rating: { score: 4.5, reviewsCount: 73 },
    price: { current: 14990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'AirPods',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Звук',
        specs: [
          { name: 'Чип', value: 'Apple H2' },
          { name: 'Пространственное аудио', value: 'Персонализированное с отслеживанием головы' },
          { name: 'Активное шумоподавление', value: 'Нет' },
          { name: 'Адаптивный звук', value: 'Нет' },
          { name: 'Режим прозрачности', value: 'Нет' },
          { name: 'Потерянное аудио', value: 'Нет' },
        ],
      },
      {
        groupName: 'Автономность',
        specs: [
          { name: 'Время работы', value: 'до 5 ч (слушание)' },
          { name: 'Зарядный чехол', value: 'USB-C' },
          { name: 'Беспроводная зарядка', value: 'Нет' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'White' },
          { name: 'Подключение', value: 'Bluetooth 5.3' },
          { name: 'Защита', value: 'IP54 (наушники и чехол)' },
          { name: 'Управление', value: 'Сенсорное (стебель)' },
          { name: 'Голосовой помощник', value: 'Hey Siri, Siri Interactions' },
          { name: 'Изоляция голоса', value: 'Да' },
          { name: 'Вес (наушники)', value: '4.3 г' },
          { name: 'Вес (чехол)', value: '34.7 г' },
        ],
      },
    ],
  },
  {
    id: '7',
    title: 'Apple AirPods 4 с ANC',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-4-anc-select-202409_FV1?wid=976&hei=916&fmt=jpeg&qlt=90&.v=Qklmb1JJend3cVIxSUxIeFBIRk96cUNGMHVRUVpqOEFiUFU4R0xNRVFxdkhJa2hkRmxkTlJIMk9SdFNSaWFNODE1UUxLT2t0cW42N3FvQzVqaGhrVVcvdmFyQU52eG9rbk9Lb1pmQWN1MGgrYWpGdS9XeFgvbS9ITnNYOEhYaG4',
    ],
    soldCount: 287,
    rating: { score: 4.7, reviewsCount: 54 },
    price: { current: 19990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'AirPods',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Звук',
        specs: [
          { name: 'Чип', value: 'Apple H2' },
          { name: 'Пространственное аудио', value: 'Персонализированное с отслеживанием головы' },
          { name: 'Активное шумоподавление', value: 'Да' },
          { name: 'Адаптивный звук', value: 'Да' },
          { name: 'Режим прозрачности', value: 'Да' },
          { name: 'Потерянное аудио', value: 'Нет' },
          { name: 'Живой перевод', value: 'Да' },
        ],
      },
      {
        groupName: 'Автономность',
        specs: [
          { name: 'Время работы', value: 'до 5 ч (слушание), до 4 ч (с ANC)' },
          { name: 'Зарядный чехол', value: 'Беспроводный USB-C' },
          { name: 'Беспроводная зарядка', value: 'Да (Apple Watch, Qi)' },
          { name: 'Динамик в чехле', value: 'Да (Find My)' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'White' },
          { name: 'Подключение', value: 'Bluetooth 5.3' },
          { name: 'Защита', value: 'IP54 (наушники и чехол)' },
          { name: 'Управление', value: 'Сенсорное (стебель)' },
          { name: 'Голосовой помощник', value: 'Hey Siri, Siri Interactions' },
          { name: 'Изоляция голоса', value: 'Да' },
          { name: 'Вес (наушники)', value: '4.3 г' },
          { name: 'Вес (чехол)', value: '34.7 г' },
        ],
      },
    ],
  },
  {
    id: '8',
    title: 'Apple AirPods Pro 3',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-pro-3-hero-select-202509?wid=976&hei=916&fmt=jpeg&qlt=90&.v=cmp4MmZ6OWxOeHNNTXh4SzlBNUpEb1RucE9zZTI5eEREaWZpY29lSld3eWVDYXovZDMyN1dXU211bjZoVlVUcWJGcXNRQnFCV0w3WVRjTExvdm1ic1YxRUxFRmRlWDBITzhnRmZ5OTRmaVdKTExiOEFsRmxtQ2Nua0tRSC83MkI',
    ],
    soldCount: 198,
    rating: { score: 4.9, reviewsCount: 41 },
    price: { current: 27990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'AirPods',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Звук',
        specs: [
          { name: 'Чип', value: 'Apple H2' },
          { name: 'Пространственное аудио', value: 'Персонализированное с отслеживанием головы' },
          { name: 'Активное шумоподавление', value: 'Да (до 4× лучше оригинальных Pro)' },
          { name: 'Адаптивный звук', value: 'Да' },
          { name: 'Режим прозрачности', value: 'Да' },
          { name: 'Живой перевод', value: 'Да' },
        ],
      },
      {
        groupName: 'Здоровье',
        specs: [
          { name: 'Пульс', value: 'Датчик пульса при тренировках' },
          { name: 'Аудиограмма', value: 'Тест слуха' },
          { name: 'Слуховой аппарат', value: 'Да' },
          { name: 'Защита слуха', value: 'Да' },
        ],
      },
      {
        groupName: 'Автономность',
        specs: [
          { name: 'Время работы', value: 'до 8 ч (с ANC), до 10 ч (прозрачность + слуховой аппарат)' },
          { name: 'Зарядный чехол', value: 'MagSafe USB-C' },
          { name: 'Беспроводная зарядка', value: 'Да (Apple Watch, Qi, MagSafe)' },
          { name: 'Динамик в чехле', value: 'Да (Find My)' },
          { name: 'Петля для шнурка', value: 'Да' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'White' },
          { name: 'Подключение', value: 'Bluetooth 5.3' },
          { name: 'Защита', value: 'IP54 (наушники и чехол)' },
          { name: 'Управление', value: 'Сенсорное (стебель)' },
          { name: 'Наконечники', value: 'Силиконовые (XS, S, M, L)' },
          { name: 'Голосовой помощник', value: 'Hey Siri, Siri Interactions' },
          { name: 'Изоляция голоса', value: 'Да' },
          { name: 'Вес (наушники)', value: '5.3 г' },
          { name: 'Вес (чехол)', value: '50.9 г' },
        ],
      },
    ],
  },
  {
    id: '9',
    title: 'Apple AirPods Max 2 Midnight',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-max-select-202409-purple_FV1?wid=976&hei=916&fmt=jpeg&qlt=90&.v=azQxRkVJKzd6V3J0aGNqWFhLMzBmdEFZMGtjOXNTYXJEaHFYa1lFVzIyUnJHdFc3SWNOdWRSclF6WTRFc2h1eFJnYUxCQWt1UDJiRlJNZVhPYkVVc2hXdERnUW81QWI5aTlucjZuTWh1dnhzQVNZV1grZHBseDduSWhqSlA3QUE',
    ],
    soldCount: 64,
    rating: { score: 4.8, reviewsCount: 19 },
    price: { current: 59990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'AirPods',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Звук',
        specs: [
          { name: 'Чип', value: 'Apple H2' },
          { name: 'Пространственное аудио', value: 'Персонализированное с отслеживанием головы' },
          { name: 'Активное шумоподавление', value: 'Да (до 1.5× лучше оригинальных Max)' },
          { name: 'Адаптивный звук', value: 'Да' },
          { name: 'Режим прозрачности', value: 'Да' },
          { name: 'Потерянное аудио', value: 'Да (через USB-C)' },
          { name: 'Живой перевод', value: 'Да' },
          { name: 'Снижение громкого звука', value: 'Да' },
        ],
      },
      {
        groupName: 'Автономность',
        specs: [
          { name: 'Время работы', value: 'до 20 ч (с ANC)' },
          { name: 'Зарядка', value: 'USB-C' },
          { name: 'Чехол', value: 'Smart Case (накрывает амбушюры)' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Midnight' },
          { name: 'Тип', value: 'Накладные (полноразмерные)' },
          { name: 'Материал', value: 'Алюминий, нержавеющая сталь, акрил' },
          { name: 'Подключение', value: 'Bluetooth 5.3' },
          { name: 'Управление', value: 'Сенсорное (Digital Crown)' },
          { name: 'Голосовой помощник', value: 'Hey Siri, Siri Interactions' },
          { name: 'Изоляция голоса', value: 'Да' },
          { name: 'Вес', value: '384.8 г' },
        ],
      },
    ],
  },
  {
    id: '10',
    title: 'Apple MacBook Pro 14" M4 Pro Space Black',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-macbook-pro-finish-select-202601-14inch-spaceblack_AV3?wid=5120&hei=3280&fmt=webp&qlt=90&.v=aXlkdGF0T0RUUVdDckNLaUc0OEE0MEhGUTRkVVZndC9KWVVLOUdiOXdHbFliNjlBeDB2TXZxU1g0Nll4dVNpMm9xbGU4dEZRUmMxczltR3FlRDU1d1FPSHBTMDVNTCtFMWdCbVRyd3l2VzlOU1YvbEhQdCtlZmMrckc2K3RtQzRoeEpCckMwYjVmYXAvS3dNV3N6N25n&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-macbook-pro-finish-select-202601-14inch-spaceblack_AV2?wid=5120&hei=3280&fmt=webp&qlt=90&.v=aXlkdGF0T0RUUVdDckNLaUc0OEE0MEhGUTRkVVZndC9KWVVLOUdiOXdHbFliNjlBeDB2TXZxU1g0Nll4dVNpMmhzU3N1ZzdHYmdHd2F0Q0JTTjFwd0FPSHBTMDVNTCtFMWdCbVRyd3l2VzlOU1YvbEhQdCtlZmMrckc2K3RtQzRFcUZTM0p3WTNTSzhmVlBIcDloRTNB&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-macbook-pro-finish-select-202601-14inch-spaceblack_AV1?wid=5120&hei=3280&fmt=webp&qlt=90&.v=aXlkdGF0T0RUUVdDckNLaUc0OEE0MEhGUTRkVVZndC9KWVVLOUdiOXdHbFliNjlBeDB2TXZxU1g0Nll4dVNpMnJkeHNiYm1zT0pXUW1JVGV5bUY5dGdPSHBTMDVNTCtFMWdCbVRyd3l2VzlOU1YvbEhQdCtlZmMrckc2K3RtQzRiblpnTTNpamtxYW5MSTI5VUhqbHBR&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-macbook-pro-finish-select-202601-14inch-spaceblack?wid=5120&hei=3280&fmt=webp&qlt=90&.v=aXlkdGF0T0RUUVdDckNLaUc0OEE0MEhGUTRkVVZndC9KWVVLOUdiOXdHbFliNjlBeDB2TXZxU1g0Nll4dVNpMjRmRTZ3YnV6NGtLcENrcTFmd0VGckVvbDF6d2tlR0VmV2RIWCtmOCtid1ZzaDZmRlFpSFhTc3dmMkpMNTNVQnFTQVNUdmQ1THNIZFcxSGxlaWpQTS9R&traceId=1',
    ],
    soldCount: 156,
    rating: { score: 4.9, reviewsCount: 47 },
    price: { current: 239990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'Mac',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Дисплей',
        specs: [
          { name: 'Диагональ', value: '14.2"' },
          { name: 'Тип', value: 'Liquid Retina XDR' },
          { name: 'Разрешение', value: '3024 × 1964 пикс.' },
          { name: 'Плотность пикселей', value: '254 пикс/дюйм' },
          { name: 'Технология', value: 'mini-LED' },
          { name: 'Частота обновления', value: '120 Гц (ProMotion)' },
          { name: 'Яркость', value: '1000 нит (典型), 1600 нит (HDR)' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple M4 Pro' },
          { name: 'Ядра CPU', value: '14 (10 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '20' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '24 ГБ unified' },
          { name: 'Накопитель', value: '512 ГБ SSD' },
        ],
      },
      {
        groupName: 'Порты и подключение',
        specs: [
          { name: 'Thunderbolt', value: '3 × Thunderbolt 5 (USB-C)' },
          { name: 'HDMI', value: '1 × HDMI 2.1' },
          { name: 'SD-карта', value: 'SDXC слот' },
          { name: 'MagSafe', value: 'Зарядка MagSafe 3' },
          { name: 'Аудио', value: '3.5 мм разъём для наушников' },
          { name: 'Wi-Fi', value: 'Wi-Fi 7 (802.11be)' },
          { name: 'Bluetooth', value: '5.4' },
        ],
      },
      {
        groupName: 'Камера и звук',
        specs: [
          { name: 'Камера', value: '12 МП Center Stage' },
          { name: 'Динамики', value: '6-колоночная система с поддержкой Dolby Atmos' },
          { name: 'Микрофоны', value: '3 микрофона с функцией подавления шума' },
        ],
      },
      {
        groupName: 'Аккумулятор',
        specs: [
          { name: 'Автономность', value: 'до 17 ч (веб-сёрфинг)' },
          { name: 'Зарядка', value: 'MagSafe 3 или USB-C' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Space Black' },
          { name: 'Материал корпуса', value: '100% переработанный алюминий' },
          { name: 'ОС', value: 'macOS Sequoia' },
          { name: 'Безопасность', value: 'Touch ID' },
          { name: 'Клавиатура', value: 'Backlit Magic Keyboard' },
          { name: 'Тачпад', value: 'Force Touch тачпад' },
          { name: 'Размеры', value: '31.26 × 22.12 × 1.55 см' },
          { name: 'Вес', value: '1.55 кг' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '11',
    title: 'Apple MacBook Pro 14" M4 Pro Silver',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-macbook-pro-finish-select-202601-14inch-silver_AV3?wid=5120&hei=3280&fmt=webp&qlt=90&.v=aXlkdGF0T0RUUVdDckNLaUc0OEE0MEhGUTRkVVZndC9KWVVLOUdiOXdHbnpzY2x4T3N3ZmxINStwTE5kUDQ0L3B2MlJ6L3NtODRFMWNEMFduN014SEVvbDF6d2tlR0VmV2RIWCtmOCtid1ZzaDZmRlFpSFhTc3dmMkpMNTNVQnE0c2xEbnBKOTVqczRGR1lRVUE1NTd3&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-macbook-pro-finish-select-202601-14inch-silver_AV2?wid=5120&hei=3280&fmt=webp&qlt=90&.v=aXlkdGF0T0RUUVdDckNLaUc0OEE0MEhGUTRkVVZndC9KWVVLOUdiOXdHbnpzY2x4T3N3ZmxINStwTE5kUDQ0L2xsTU9CZXhzSzAwb1pTN09tQ3FEVTBvbDF6d2tlR0VmV2RIWCtmOCtid1ZzaDZmRlFpSFhTc3dmMkpMNTNVQnFyMHI2ZUJjbWo5clBRTmNDMkdReWdn&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-macbook-pro-finish-select-202601-14inch-silver_AV1?wid=5120&hei=3280&fmt=webp&qlt=90&.v=aXlkdGF0T0RUUVdDckNLaUc0OEE0MEhGUTRkVVZndC9KWVVLOUdiOXdHbnpzY2x4T3N3ZmxINStwTE5kUDQ0L3kycG5rSmFSYlFlU3JVaTlXMmliMGtvbDF6d2tlR0VmV2RIWCtmOCtid1ZzaDZmRlFpSFhTc3dmMkpMNTNVQnFDOFc5TENRV0tscFJUWE94Vm9BWUlB&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-macbook-pro-finish-select-202601-14inch-silver?wid=5120&hei=3280&fmt=webp&qlt=90&.v=aXlkdGF0T0RUUVdDckNLaUc0OEE0MEhGUTRkVVZndC9KWVVLOUdiOXdHbnpzY2x4T3N3ZmxINStwTE5kUDQ0Lzh3djZBZnNaM0piSnp2bkxicDY2ZlRZNzNqei9rOFR5dnVIK2I3YjBmTWcwQjJ5THFYUTNqb3hPd0k3K0Q2czhSY1JNNE80ZFBDbVhzTHFpbER4STZn&traceId=1',
    ],
    soldCount: 143,
    rating: { score: 4.9, reviewsCount: 42 },
    price: { current: 239990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'Mac',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Дисплей',
        specs: [
          { name: 'Диагональ', value: '14.2"' },
          { name: 'Тип', value: 'Liquid Retina XDR' },
          { name: 'Разрешение', value: '3024 × 1964 пикс.' },
          { name: 'Плотность пикселей', value: '254 пикс/дюйм' },
          { name: 'Технология', value: 'mini-LED' },
          { name: 'Частота обновления', value: '120 Гц (ProMotion)' },
          { name: 'Яркость', value: '1000 нит (典型), 1600 нит (HDR)' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple M4 Pro' },
          { name: 'Ядра CPU', value: '14 (10 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '20' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '24 ГБ unified' },
          { name: 'Накопитель', value: '512 ГБ SSD' },
        ],
      },
      {
        groupName: 'Порты и подключение',
        specs: [
          { name: 'Thunderbolt', value: '3 × Thunderbolt 5 (USB-C)' },
          { name: 'HDMI', value: '1 × HDMI 2.1' },
          { name: 'SD-карта', value: 'SDXC слот' },
          { name: 'MagSafe', value: 'Зарядка MagSafe 3' },
          { name: 'Аудио', value: '3.5 мм разъём для наушников' },
          { name: 'Wi-Fi', value: 'Wi-Fi 7 (802.11be)' },
          { name: 'Bluetooth', value: '5.4' },
        ],
      },
      {
        groupName: 'Камера и звук',
        specs: [
          { name: 'Камера', value: '12 МП Center Stage' },
          { name: 'Динамики', value: '6-колоночная система с поддержкой Dolby Atmos' },
          { name: 'Микрофоны', value: '3 микрофона с функцией подавления шума' },
        ],
      },
      {
        groupName: 'Аккумулятор',
        specs: [
          { name: 'Автономность', value: 'до 17 ч (веб-сёрфинг)' },
          { name: 'Зарядка', value: 'MagSafe 3 или USB-C' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Silver' },
          { name: 'Материал корпуса', value: '100% переработанный алюминий' },
          { name: 'ОС', value: 'macOS Sequoia' },
          { name: 'Безопасность', value: 'Touch ID' },
          { name: 'Клавиатура', value: 'Backlit Magic Keyboard' },
          { name: 'Тачпад', value: 'Force Touch тачпад' },
          { name: 'Размеры', value: '31.26 × 22.12 × 1.55 см' },
          { name: 'Вес', value: '1.55 кг' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '12',
    title: 'Apple Watch SE 3 44 мм Midnight',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MHYK4ref_SR_SE_VW_PF+watch-case-44-aluminum-midnight-nc-se3_VW_PF+watch-face-44-aluminum-midnight-se3_VW_PF?wid=5120&hei=3280&bgc=fafafa&trim=1&fmt=p-jpg&qlt=80&.v=bmp6WmFFZENEMlFoVlZZVmYybU0yWnN3bmZMYXBUV0xvcU1EeGl4ejE5cC9pd1RRamNxTEJTRVAwWTdMVDhpVWlBUlNSVnl1TVl5SlgrcGVSRnNNYlhlcnk1TlBIT2pRZGdqOElhSGc4TEg5TlpLLzFsUGcrdUp2UlNmWUVsSlpZNXJOK0VWV044RklnQXVzN1p6UWMwUVN3R3VxZWhYYXgwOHljYmZFMXBocmMyRTN3NCt6QkoxaUdRb0FBay9VYktGTHdENW9lYUFnak5pcy9ReEdDZWJCUmh0M0MzODJjOHNRNG5aRStCZDd6Um5CU05vWEFTZkZzTW4rR3lhNQ',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MHYK4ref_SR_SE_VW_34FR+watch-case-44-aluminum-midnight-nc-se3_VW_34FR+watch-face-44-aluminum-midnight-se3_VW_34FR?wid=5120&hei=3280&bgc=fafafa&trim=1&fmt=p-jpg&qlt=80&.v=bmp6WmFFZENEMlFoVlZZVmYybU0yYnFPOHloWjNpK0lhdm45WTdiR1R1VlNpbmxWRXZGZnY4LzZZMkcwekpTb1VxdVkrbFpOQ3hIcTVRcDJCM1krUm5qblBjd2JiYm5raG5NaEt4aVI1UUlsbzEzVXl1Vmk5NFIvT0hFSlVVNHdpS2p6UE9iQ1Z2bWhzRFBHUjV2R2JOSm5XWGtDU0t4VVQwQ0ZnMHNnV1ZqMmFiRXE4YTdHOUNzeVhiUmVNZ0lpaGE5a21iNjNmZ25ST0hCamcvSkRsVTZDMkxXRVd5VzZuMnYreFI0MFA0S1JlSmQwRm5Ud0lLNlpBb1AyMXJ6Rw',
    ],
    soldCount: 178,
    rating: { score: 4.6, reviewsCount: 34 },
    price: { current: 26990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'Apple Watch',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Дисплей',
        specs: [
          { name: 'Диагональ', value: '44 мм' },
          { name: 'Тип', value: 'OLED Retina' },
          { name: 'Разрешение', value: '396 × 484 пикс.' },
          { name: 'Яркость', value: 'до 1000 нит' },
          { name: 'Защитное стекло', value: 'Ion-X (стекло)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple S9 SiP' },
          { name: 'Ядра CPU', value: '2' },
          { name: 'Чип связи', value: 'W3' },
          { name: 'Вместимость', value: '32 ГБ' },
        ],
      },
      {
        groupName: 'Датчики',
        specs: [
          { name: 'Пульс', value: 'Оптический датчик сердечного ритма (2-е поколение)' },
          { name: 'Температура', value: 'Нет' },
          { name: 'Высотомер', value: 'Always-on' },
          { name: 'Компас', value: 'Встроенный' },
          { name: 'Акселерометр', value: 'Да' },
          { name: 'Гироскоп', value: 'Да' },
          { name: 'Датчик освещённости', value: 'Да' },
          { name: 'Обнаружение падения', value: 'Да' },
          { name: 'Экстренный вызов SOS', value: 'Да' },
        ],
      },
      {
        groupName: 'Связь',
        specs: [
          { name: 'GPS', value: 'GPS, GLONASS, Galileo, BeiDou' },
          { name: 'Wi-Fi', value: '802.11b/g/n 2.4 ГГц' },
          { name: 'Bluetooth', value: '5.3' },
          { name: 'NFC', value: 'Да (Apple Pay)' },
          { name: 'LTE', value: 'Нет (только GPS)' },
        ],
      },
      {
        groupName: 'Аккумулятор',
        specs: [
          { name: 'Автономность', value: 'до 18 ч (обычный режим)' },
          { name: 'Зарядка', value: 'Магнитная USB-C зарядка' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет корпуса', value: 'Midnight' },
          { name: 'Материал корпуса', value: 'Алюминий' },
          { name: 'Ремешок', value: 'Sport Band (оранжевый)' },
          { name: 'Водозащита', value: 'WR50 (50 м)' },
          { name: 'ОС', value: 'watchOS 11' },
          { name: 'Безопасность', value: 'Код-замок' },
          { name: 'Размеры', value: '44 × 38 × 10.7 мм' },
          { name: 'Вес', value: '33 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '13',
    title: 'Apple TV 4K (3-го поколения) 128 ГБ',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/apple-tv-4k-hero-select-202210?wid=940&hei=1112&fmt=p-jpg&qlt=95&.v=a3VoZW85YUhreXN3ZFlSUDc3a0tqdU1qeWRTYWRhVU5NM3d6SkhmNzkxTjdKMGdNUjJ3Q0dzSU9tc2pOeGwxbXg4ZHpEbm5XWGdaM3BiNVRDaG55UktNaUdBMSt0VkxKZ2NWelk1alBpUVVXZEdHNUFPR0hYUU12cjI0VlFzM1A',
    ],
    soldCount: 89,
    rating: { score: 4.7, reviewsCount: 22 },
    price: { current: 16990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'Apple TV',
    year: '2022',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A15 Bionic' },
          { name: 'Ядра GPU', value: '5' },
          { name: 'Накопитель', value: '128 ГБ' },
        ],
      },
      {
        groupName: 'Видеовыход',
        specs: [
          { name: 'Разрешение', value: '4K HDR' },
          { name: 'HDR', value: 'Dolby Vision, HDR10+' },
          { name: 'Частота обновления', value: 'до 60 кадр/с' },
        ],
      },
      {
        groupName: 'Звук',
        specs: [
          { name: 'Аудио', value: 'Dolby Atmos,的空间 аудио' },
          { name: 'Аудиовыход', value: 'HDMI eARC' },
        ],
      },
      {
        groupName: 'Подключение',
        specs: [
          { name: 'Wi-Fi', value: 'Wi-Fi 6 (802.11ax)' },
          { name: 'Bluetooth', value: '5.0' },
          { name: 'Ethernet', value: '10/100 Мбит/с (только 128 ГБ)' },
          { name: 'HDMI', value: '1 × HDMI 2.1' },
          { name: 'USB-C', value: 'Да (зарядка пульта)' },
        ],
      },
      {
        groupName: 'Пульт',
        specs: [
          { name: 'Пульт', value: 'Apple TV Remote (USB-C)' },
          { name: 'Навигация', value: 'Сенсорная панель' },
          { name: 'Голосовой помощник', value: 'Siri (на пульте)' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'ОС', value: 'tvOS' },
          { name: 'Размеры', value: '9.3 × 9.3 × 3.1 см' },
          { name: 'Вес', value: '214 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '14',
    title: 'Apple iPhone 17 Pro 256 ГБ Cosmic Orange',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-finish-select-202509-6-3inch-cosmicorange_AV3?wid=5120&hei=2880&fmt=webp&qlt=90&.v=NUNzdzNKR0FJbmhKWm5YamRHb05tUzkyK3hWak1ybHhtWDkwUXVINFc0RUlmWnJkM2NiV2hVVVF2ZE1VdGpQZUdVOXBJM0tlanRWNXp5VTBpa2p2TUtyeklvaXVkOCtBWFpMeWRrK0lya3dQSjVrSzRsUkk3OGQ3bDdIU2QzMFdGVkM4SmQrWXZLOGdmeXVtbUR3d2dn&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-finish-select-202509-6-3inch-cosmicorange_AV1?wid=5120&hei=2880&fmt=webp&qlt=90&.v=NUNzdzNKR0FJbmhKWm5YamRHb05tUzkyK3hWak1ybHhtWDkwUXVINFc0RUlmWnJkM2NiV2hVVVF2ZE1VdGpQZTI3b045dUFHd0tTS1VURkFwVjdWRTZyeklvaXVkOCtBWFpMeWRrK0lya3dQSjVrSzRsUkk3OGQ3bDdIU2QzMFdXejRTeGhicWR4SE1PMExQQ3NGeXF3&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-finish-select-202509-6-3inch-cosmicorange?wid=5120&hei=2880&fmt=webp&qlt=90&.v=NUNzdzNKR0FJbmhKWm5YamRHb05tUzkyK3hWak1ybHhtWDkwUXVINFc0RUlmWnJkM2NiV2hVVVF2ZE1VdGpQZWhsQTdPYWVGbmdIenAvNE9qYmZVYVFDb1F2RTNvUEVHRkpGaGtOSVFHak5NTEhXRE11VU1QNVo2eDJsWlpuWHRlLys5ZkozSXJXZWZXNk8rZDF5S0V3&traceId=1',
    ],
    soldCount: 412,
    rating: { score: 4.8, reviewsCount: 67 },
    price: { current: 129990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPhone',
    year: '2025',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '6.3"' },
          { name: 'Тип', value: 'Super Retina XDR OLED' },
          { name: 'Разрешение', value: '2622 × 1206 пикс.' },
          { name: 'Плотность пикселей', value: '460 пикс/дюйм' },
          { name: 'Частота обновления', value: '120 Гц (ProMotion)' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Always-On дисплей', value: 'Да' },
          { name: 'Dynamic Island', value: 'Да' },
          { name: 'Яркость', value: '1000 нит (典型), 1600 нит (HDR), 2000 нит (наружная)' },
          { name: 'Защитное стекло', value: 'Ceramic Shield (поколение 2)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A19 Pro' },
          { name: 'Ядра CPU', value: '6 (2 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '6' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '12 ГБ' },
          { name: 'Накопитель', value: '256 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '48 МП Fusion, ƒ/1.78' },
          { name: 'Сверхширокоугольная', value: '48 МП Ultra Wide, ƒ/2.2' },
          { name: 'Телефото', value: '12 МП, 5× оптический зум, ƒ/2.8' },
          { name: 'Видео', value: '4K 120 кадр/с, Dolby Vision, ProRes' },
          { name: 'Оптический зум', value: '0.5×, 1×, 2×, 5×' },
          { name: 'Фронтальная', value: '18 МП Center Stage' },
          { name: 'Camera Control', value: 'Да' },
          { name: 'Macro', value: 'Да' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '3 877 мАч' },
          { name: 'Автономность', value: 'до 27 ч (воспроизведение видео)' },
          { name: 'Быстрая зарядка', value: 'до 50% за 35 мин (адаптер 20 Вт)' },
          { name: 'Беспроводная зарядка', value: 'MagSafe 25 Вт, Qi2 15 Вт' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Cosmic Orange' },
          { name: 'Материал корпуса', value: 'Алюминий (цельный)' },
          { name: 'Безопасность', value: 'Face ID' },
          { name: 'ОС', value: 'iOS 19' },
          { name: 'Степень защиты', value: 'IP68' },
          { name: 'Action Button', value: 'Да' },
          { name: 'Размеры', value: '146.9 × 71.5 × 8.3 мм' },
          { name: 'Вес', value: '194 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '15',
    title: 'Apple iPhone 17 Pro Max 256 ГБ Deep Blue',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-finish-select-202509-6-9inch-deepblue_AV3?wid=5120&hei=2880&fmt=webp&qlt=90&.v=NUNzdzNKR0FJbmhKWm5YamRHb05tUzkyK3hWak1ybHhtWDkwUXVINFc0RWhhOHJGRUNHdlh6a3VuZVVqdnNrNVJ2dnZ6eHdCQ0dUd3RuYU1ZcENUSHdDb1F2RTNvUEVHRkpGaGtOSVFHak5NTEhXRE11VU1QNVo2eDJsWlpuWHQ1V3E2amljcVUyYTdYMlk2dDNTTllR&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-finish-select-202509-6-9inch-deepblue_AV1?wid=5120&hei=2880&fmt=webp&qlt=90&.v=NUNzdzNKR0FJbmhKWm5YamRHb05tUzkyK3hWak1ybHhtWDkwUXVINFc0RWhhOHJGRUNHdlh6a3VuZVVqdnNrNWg5UFBFaEh4RWhiVUdVWWFjbERrL3dDb1F2RTNvUEVHRkpGaGtOSVFHak5NTEhXRE11VU1QNVo2eDJsWlpuWHRwYlVVc0liQnJ0TTMwbEt5SExvaWxn&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-finish-select-202509-6-9inch-deepblue?wid=5120&hei=2880&fmt=webp&qlt=90&.v=NUNzdzNKR0FJbmhKWm5YamRHb05tUzkyK3hWak1ybHhtWDkwUXVINFc0RWhhOHJGRUNHdlh6a3VuZVVqdnNrNXVHdDcxbVFRSnhaQ0pnV1pOaG5KaGhNQnJMcnc4RkxJd3ZMc3hKZVVFWHREelVULzVXd2xCbVltNVMyUXhsYlBpMEowc2xaa1ByZlpMdyt3ZFlhVkhn&traceId=1',
    ],
    soldCount: 356,
    rating: { score: 4.9, reviewsCount: 78 },
    price: { current: 149990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPhone',
    year: '2025',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '6.9"' },
          { name: 'Тип', value: 'Super Retina XDR OLED' },
          { name: 'Разрешение', value: '2868 × 1320 пикс.' },
          { name: 'Плотность пикселей', value: '460 пикс/дюйм' },
          { name: 'Частота обновления', value: '120 Гц (ProMotion)' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Always-On дисплей', value: 'Да' },
          { name: 'Dynamic Island', value: 'Да' },
          { name: 'Яркость', value: '1000 нит (典型), 1600 нит (HDR), 2000 нит (наружная)' },
          { name: 'Защитное стекло', value: 'Ceramic Shield (поколение 2)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A19 Pro' },
          { name: 'Ядра CPU', value: '6 (2 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '6' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '12 ГБ' },
          { name: 'Накопитель', value: '256 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '48 МП Fusion, ƒ/1.78' },
          { name: 'Сверхширокоугольная', value: '48 МП Ultra Wide, ƒ/2.2' },
          { name: 'Телефото', value: '12 МП, 5× оптический зум, ƒ/2.8' },
          { name: 'Видео', value: '4K 120 кадр/с, Dolby Vision, ProRes' },
          { name: 'Оптический зум', value: '0.5×, 1×, 2×, 5×' },
          { name: 'Фронтальная', value: '18 МП Center Stage' },
          { name: 'Camera Control', value: 'Да' },
          { name: 'Macro', value: 'Да' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '4 685 мАч' },
          { name: 'Автономность', value: 'до 33 ч (воспроизведение видео)' },
          { name: 'Быстрая зарядка', value: 'до 50% за 35 мин (адаптер 20 Вт)' },
          { name: 'Беспроводная зарядка', value: 'MagSafe 25 Вт, Qi2 15 Вт' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Deep Blue' },
          { name: 'Материал корпуса', value: 'Титан класса 5' },
          { name: 'Безопасность', value: 'Face ID' },
          { name: 'ОС', value: 'iOS 19' },
          { name: 'Степень защиты', value: 'IP68' },
          { name: 'Action Button', value: 'Да' },
          { name: 'Размеры', value: '163.0 × 77.6 × 8.3 мм' },
          { name: 'Вес', value: '227 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '16',
    title: 'Apple MacBook Neo 13" M4 Silver',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-neo-color-select-202603-silver_AV3?wid=5120&hei=3280&fmt=webp&qlt=90&.v=TytZbDBUUnRqRElRcFlBSHpmZVVDNFdhaFd1bmVlZEFaaDd5ZjhzZmNGZzdmaSttajVJUFdIQ0hBaUpMODBKd0E0ZWxMVGt3djRUV0FHWk92REs5YjAxSlgrVWMrMzU1OXo2c2JyNjJZTGdoMGhMcEN4UVNtcUpGWW9zaWNPbis&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-neo-color-select-202603-silver_AV2?wid=5120&hei=3280&fmt=webp&qlt=90&.v=TytZbDBUUnRqRElRcFlBSHpmZVVDNFdhaFd1bmVlZEFaaDd5ZjhzZmNGZ3pFa3Z0aXlpclR5elBhNS9oU2pzSUE0ZWxMVGt3djRUV0FHWk92REs5YjAxSlgrVWMrMzU1OXo2c2JyNjJZTGhPRUdIVHVQU25LVUJhKzBCTk9seFg&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-neo-color-select-202603-silver_AV1?wid=5120&hei=3280&fmt=webp&qlt=90&.v=TytZbDBUUnRqRElRcFlBSHpmZVVDNFdhaFd1bmVlZEFaaDd5ZjhzZmNGalZReGhvT0VRdCtIa3J1eDBIRnNYUUE0ZWxMVGt3djRUV0FHWk92REs5YjAxSlgrVWMrMzU1OXo2c2JyNjJZTGgwNlJrSk9kVWZHYWt6MWx2RUNKQ0w&traceId=1',
    ],
    soldCount: 234,
    rating: { score: 4.8, reviewsCount: 56 },
    price: { current: 109990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'Mac',
    year: '2025',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Дисплей',
        specs: [
          { name: 'Диагональ', value: '13.6"' },
          { name: 'Тип', value: 'Liquid Retina' },
          { name: 'Разрешение', value: '2560 × 1664 пикс.' },
          { name: 'Плотность пикселей', value: '224 пикс/дюйм' },
          { name: 'Частота обновления', value: '60 Гц' },
          { name: 'Яркость', value: '500 нит' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple M4' },
          { name: 'Ядра CPU', value: '10 (4 производительных + 6 энергоэффективных)' },
          { name: 'Ядра GPU', value: '10' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '16 ГБ unified' },
          { name: 'Накопитель', value: '256 ГБ SSD' },
        ],
      },
      {
        groupName: 'Порты и подключение',
        specs: [
          { name: 'Thunderbolt', value: '2 × Thunderbolt 4 (USB-C)' },
          { name: 'MagSafe', value: 'Зарядка MagSafe 3' },
          { name: 'Аудио', value: '3.5 мм разъём для наушников' },
          { name: 'Wi-Fi', value: 'Wi-Fi 6E (802.11ax)' },
          { name: 'Bluetooth', value: '5.3' },
        ],
      },
      {
        groupName: 'Камера и звук',
        specs: [
          { name: 'Камера', value: '12 МП Center Stage' },
          { name: 'Динамики', value: 'Стерео с поддержкой Dolby Atmos' },
          { name: 'Микрофоны', value: '3 микрофона с функцией подавления шума' },
        ],
      },
      {
        groupName: 'Аккумулятор',
        specs: [
          { name: 'Автономность', value: 'до 18 ч (веб-сёрфинг)' },
          { name: 'Зарядка', value: 'MagSafe 3 или USB-C' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Silver' },
          { name: 'Материал корпуса', value: '100% переработанный алюминий' },
          { name: 'ОС', value: 'macOS Sequoia' },
          { name: 'Безопасность', value: 'Touch ID' },
          { name: 'Клавиатура', value: 'Backlit Magic Keyboard' },
          { name: 'Тачпад', value: 'Force Touch тачпад' },
          { name: 'Размеры', value: '30.41 × 21.24 × 1.13 см' },
          { name: 'Вес', value: '1.24 кг' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '17',
    title: 'Apple MacBook Neo 13" M4 Blush',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-neo-color-select-202603-blush_AV3?wid=5120&hei=3280&fmt=webp&qlt=90&.v=TytZbDBUUnRqRElRcFlBSHpmZVVDNFdhaFd1bmVlZEFaaDd5ZjhzZmNGaVVCSWNSVUIxUThzWlpwSEI3Z1cxYWZvSGF2dFhlaXl5ZzZDVTRMdEVvNll2UjRaSC9URTlmd0FSb1ZTWjRnb3VNZm9yR3NLRm9xNlg0VUJhMFY2dkM&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-neo-color-select-202603-blush_AV2?wid=5120&hei=3280&fmt=webp&qlt=90&.v=TytZbDBUUnRqRElRcFlBSHpmZVVDNFdhaFd1bmVlZEFaaDd5ZjhzZmNGaStpRVl4UjU1RlFZN1NHN1M2a2JEN2ZvSGF2dFhlaXl5ZzZDVTRMdEVvNll2UjRaSC9URTlmd0FSb1ZTWjRnb3MrRjMvL1MxUUwvRHZwUmlDT2ltTkk&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-neo-color-select-202603-blush_AV1?wid=5120&hei=3280&fmt=webp&qlt=90&.v=TytZbDBUUnRqRElRcFlBSHpmZVVDNFdhaFd1bmVlZEFaaDd5ZjhzZmNGaEtPeVlsckZOZkRhTXZYMzhWU01YWmZvSGF2dFhlaXl5ZzZDVTRMdEVvNll2UjRaSC9URTlmd0FSb1ZTWjRnb3U5OWlwdEJPTjdwMkh3Z3kvRkpFYWc&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/macbook-neo-color-select-202603-blush?wid=5120&hei=3280&fmt=webp&qlt=90&.v=TytZbDBUUnRqRElRcFlBSHpmZVVDNFdhaFd1bmVlZEFaaDd5ZjhzZmNGaTJXcGV0S1RvcFFEZ3lwQkF6ZjJpUGllL1JtdmgzcGVIUDRDUVJnTDZxRjN2TUJEekVlZHpBZVEwZnY0SVpRaUFSYk9JNHJaUWt3Zm9IL2hlOVhoTGs&traceId=1',
    ],
    soldCount: 198,
    rating: { score: 4.8, reviewsCount: 48 },
    price: { current: 109990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'Mac',
    year: '2025',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Дисплей',
        specs: [
          { name: 'Диагональ', value: '13.6"' },
          { name: 'Тип', value: 'Liquid Retina' },
          { name: 'Разрешение', value: '2560 × 1664 пикс.' },
          { name: 'Плотность пикселей', value: '224 пикс/дюйм' },
          { name: 'Частота обновления', value: '60 Гц' },
          { name: 'Яркость', value: '500 нит' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple M4' },
          { name: 'Ядра CPU', value: '10 (4 производительных + 6 энергоэффективных)' },
          { name: 'Ядра GPU', value: '10' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '16 ГБ unified' },
          { name: 'Накопитель', value: '256 ГБ SSD' },
        ],
      },
      {
        groupName: 'Порты и подключение',
        specs: [
          { name: 'Thunderbolt', value: '2 × Thunderbolt 4 (USB-C)' },
          { name: 'MagSafe', value: 'Зарядка MagSafe 3' },
          { name: 'Аудио', value: '3.5 мм разъём для наушников' },
          { name: 'Wi-Fi', value: 'Wi-Fi 6E (802.11ax)' },
          { name: 'Bluetooth', value: '5.3' },
        ],
      },
      {
        groupName: 'Камера и звук',
        specs: [
          { name: 'Камера', value: '12 МП Center Stage' },
          { name: 'Динамики', value: 'Стерео с поддержкой Dolby Atmos' },
          { name: 'Микрофоны', value: '3 микрофона с функцией подавления шума' },
        ],
      },
      {
        groupName: 'Аккумулятор',
        specs: [
          { name: 'Автономность', value: 'до 18 ч (веб-сёрфинг)' },
          { name: 'Зарядка', value: 'MagSafe 3 или USB-C' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Blush' },
          { name: 'Материал корпуса', value: '100% переработанный алюминий' },
          { name: 'ОС', value: 'macOS Sequoia' },
          { name: 'Безопасность', value: 'Touch ID' },
          { name: 'Клавиатура', value: 'Backlit Magic Keyboard' },
          { name: 'Тачпад', value: 'Force Touch тачпад' },
          { name: 'Размеры', value: '30.41 × 21.24 × 1.13 см' },
          { name: 'Вес', value: '1.24 кг' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '18',
    title: 'Apple iPhone 17e 128 ГБ Black',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17e-finish-select-202603-black_AV2?wid=5120&hei=2880&fmt=webp&qlt=90&.v=WEw4Mm90aWNESFd6NGRURjZZeWczYmpqWk1KSDNrTSt2a0ZJNEFxNVkvVVM2SWozMndHRW1PenJ4eGFlNmZNN0pFd0xhWDVibStLdGRYRmxkNGI4VTR2UjRaSC9URTlmd0FSb1ZTWjRnb3NWaDUxdUh6SjZWT3RKcHBOOS9udzI&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17e-finish-select-202603-black_AV1?wid=5120&hei=2880&fmt=webp&qlt=90&.v=WEw4Mm90aWNESFd6NGRURjZZeWczYmpqWk1KSDNrTSt2a0ZJNEFxNVkvV0lteU5GRWp1ZEt4a2h6aDVFM041MUpFd0xhWDVibStLdGRYRmxkNGI4VTR2UjRaSC9URTlmd0FSb1ZTWjRnb3RBMktEWGVURG9zdS9vK2laQW1mZWQ&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17e-finish-select-202603-black?wid=5120&hei=2880&fmt=webp&qlt=90&.v=WEw4Mm90aWNESFd6NGRURjZZeWczYmpqWk1KSDNrTSt2a0ZJNEFxNVkvVTBHUk0xampKNG9lbGhBOGJDblFiazg5ZFJsR0hrQnFVeEVSbnU0TWlpU0ttSzg4U0NFZWZNZGRZbjQxejhOM3hDWXM5dFpjWHEyQTA2UDNBMGNmTWQ&traceId=1',
    ],
    soldCount: 445,
    rating: { score: 4.6, reviewsCount: 93 },
    price: { current: 64990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPhone',
    year: '2025',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '6.1"' },
          { name: 'Тип', value: 'Super Retina XDR OLED' },
          { name: 'Разрешение', value: '2532 × 1170 пикс.' },
          { name: 'Плотность пикселей', value: '460 пикс/дюйм' },
          { name: 'Частота обновления', value: '60 Гц' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Dynamic Island', value: 'Нет (Notch)' },
          { name: 'Яркость', value: '1000 нит (典型), 1600 нит (HDR), 2000 нит (наружная)' },
          { name: 'Защитное стекло', value: 'Ceramic Shield' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A19' },
          { name: 'Ядра CPU', value: '6 (2 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '4' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '8 ГБ' },
          { name: 'Накопитель', value: '128 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '48 МП Fusion, ƒ/1.6' },
          { name: 'Видео', value: '4K 60 кадр/с, Dolby Vision' },
          { name: 'Оптический зум', value: '1×, 2×' },
          { name: 'Фронтальная', value: '12 МП TrueDepth, ƒ/1.9' },
          { name: 'Camera Control', value: 'Нет' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '3 561 мАч' },
          { name: 'Автономность', value: 'до 26 ч (воспроизведение видео)' },
          { name: 'Быстрая зарядка', value: 'до 50% за 35 мин (адаптер 20 Вт)' },
          { name: 'Беспроводная зарядка', value: 'MagSafe 15 Вт, Qi2 15 Вт' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Black' },
          { name: 'Материал корпуса', value: 'Алюминий' },
          { name: 'Безопасность', value: 'Face ID' },
          { name: 'ОС', value: 'iOS 19' },
          { name: 'Степень защиты', value: 'IP68' },
          { name: 'Action Button', value: 'Да' },
          { name: 'Размеры', value: '147.6 × 71.6 × 7.8 мм' },
          { name: 'Вес', value: '170 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '19',
    title: 'Apple iPad mini 7 128 ГБ Blue',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-mini-storage-select-gallery-202410-blue?wid=5120&hei=2880&fmt=webp&qlt=90&.v=bFU5N2g4aXJnREUycExQajkrUEtxVTRQdUZOUjNqOGs3RHc3NGcvUnpJckdTUFZONUxMWEgxK0pDa2Y5Zi93WU9MekhWSGZtV1pvV240QzNuTk80VS9jVTIwcEJjL3Axby9SNE1La0phb1VMWnVmT1FZWitJbkFYcS9vNEVNdmE&traceId=1',
    ],
    soldCount: 167,
    rating: { score: 4.7, reviewsCount: 39 },
    price: { current: 52990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPad',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '8.3"' },
          { name: 'Тип', value: 'Liquid Retina IPS LCD' },
          { name: 'Разрешение', value: '2266 × 1488 пикс.' },
          { name: 'Плотность пикселей', value: '326 пикс/дюйм' },
          { name: 'Частота обновления', value: '60 Гц' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Яркость', value: '500 нит' },
          { name: 'Защитное стекло', value: 'Олеофобное покрытие' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A17 Pro' },
          { name: 'Ядра CPU', value: '6 (2 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '5' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '8 ГБ' },
          { name: 'Накопитель', value: '128 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '12 МП, ƒ/1.8' },
          { name: 'Видео', value: '4K 60 кадр/с' },
          { name: 'Фронтальная', value: '12 МП Ultra Wide, Center Stage' },
        ],
      },
      {
        groupName: 'Apple Pencil',
        specs: [
          { name: 'Apple Pencil Pro', value: 'Поддержка' },
          { name: 'Apple Pencil (USB-C)', value: 'Поддержка' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '19.3 Вт·ч' },
          { name: 'Автономность', value: 'до 10 ч (веб-сёрфинг)' },
          { name: 'Зарядка', value: 'USB-C' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Blue' },
          { name: 'Материал корпуса', value: '100% переработанный алюминий' },
          { name: 'Безопасность', value: 'Touch ID' },
          { name: 'ОС', value: 'iPadOS 18' },
          { name: 'Размеры', value: '195.4 × 134.7 × 6.3 мм' },
          { name: 'Вес', value: '293 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '20',
    title: 'Apple iPad mini 7 128 ГБ Starlight',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-mini-finish-select-gallery-202410-starlight-wificell_AV2?wid=5120&hei=2880&fmt=webp&qlt=90&.v=eDJDc00wczl1QWk5QmpVYitFNXQwN0Y2ME45L1lWWDhkYWVYaTNEZnBvRFV5cndHazlKcHZSL01JcVNkd3dCcjNXS1J3UDBwajJhTWxQc3NqNmloYjlJVUY1eklwSElSL2pyWFgySnpoc1FWYUQyemVEUlZ1WEdDVXExYzQ2eVMveWFHQTd3WDFDWUxscldabkZuTlYzNXFNVzc5YkZmK2I4YzJ4ZndkZUdj&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-mini-finish-select-gallery-202410-starlight-wificell_AV1?wid=5120&hei=2880&fmt=webp&qlt=90&.v=eDJDc00wczl1QWk5QmpVYitFNXQwN0Y2ME45L1lWWDhkYWVYaTNEZnBvRFV5cndHazlKcHZSL01JcVNkd3dCcjZPTFV5RkNCZEJKNXdBUGJvbHpMek5JVUY1eklwSElSL2pyWFgySnpoc1FWYUQyemVEUlZ1WEdDVXExYzQ2eVNOWWxYZXZ1SC9ic3pPNkdzcnV5VlYzNXFNVzc5YkZmK2I4YzJ4ZndkZUdj&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-mini-finish-select-gallery-202410-starlight-wificell?wid=5120&hei=2880&fmt=webp&qlt=90&.v=eDJDc00wczl1QWk5QmpVYitFNXQwN0Y2ME45L1lWWDhkYWVYaTNEZnBvRFV5cndHazlKcHZSL01JcVNkd3dCclExR0ltRk1Jdmdna00xLzZmcFBCTENSTUMybCtXNXZpclhWeFpYZUcvRk9MMGVHUi8weFBYOEFFYUZVbWVJS0xneTBpN0VWZG5sOUhCWXZQTkxCM0JR&traceId=1',
    ],
    soldCount: 154,
    rating: { score: 4.7, reviewsCount: 35 },
    price: { current: 52990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPad',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '8.3"' },
          { name: 'Тип', value: 'Liquid Retina IPS LCD' },
          { name: 'Разрешение', value: '2266 × 1488 пикс.' },
          { name: 'Плотность пикселей', value: '326 пикс/дюйм' },
          { name: 'Частота обновления', value: '60 Гц' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Яркость', value: '500 нит' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A17 Pro' },
          { name: 'Ядра CPU', value: '6 (2 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '5' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '8 ГБ' },
          { name: 'Накопитель', value: '128 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '12 МП, ƒ/1.8' },
          { name: 'Видео', value: '4K 60 кадр/с' },
          { name: 'Фронтальная', value: '12 МП Ultra Wide, Center Stage' },
        ],
      },
      {
        groupName: 'Apple Pencil',
        specs: [
          { name: 'Apple Pencil Pro', value: 'Поддержка' },
          { name: 'Apple Pencil (USB-C)', value: 'Поддержка' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '19.3 Вт·ч' },
          { name: 'Автономность', value: 'до 10 ч (веб-сёрфинг)' },
          { name: 'Зарядка', value: 'USB-C' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Starlight' },
          { name: 'Материал корпуса', value: '100% переработанный алюминий' },
          { name: 'Безопасность', value: 'Touch ID' },
          { name: 'ОС', value: 'iPadOS 18' },
          { name: 'Размеры', value: '195.4 × 134.7 × 6.3 мм' },
          { name: 'Вес', value: '293 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '21',
    title: 'Apple iPhone Air 256 ГБ Light Gold',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-air-finish-select-202509-lightgold_AV2?wid=5120&hei=2880&fmt=webp&qlt=90&.v=NUpaQVl1bitSNmJWZUdKdi9QZHhsQnMyOXpiUEVyWXc0UFVFMUg1R1ZtcFVDa0ZBMDhvSHhBTmFlZ0E4dXA1VDBoUVhuTWlrY2hIK090ZGZZbk9HeEJWb1BiTjRORlc1Y1lKU3JWempySktPQThETEx5K2lETXBoTWtWR3ZGV3ZmbW94YnYxc1YvNXZ4emJGL0IxNFp3&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-air-finish-select-202509-lightgold_AV1?wid=5120&hei=2880&fmt=webp&qlt=90&.v=NUpaQVl1bitSNmJWZUdKdi9QZHhsQnMyOXpiUEVyWXc0UFVFMUg1R1ZtcFU1RUlyWVlCYmpRbFo1TUNLTFVocTBoUVhuTWlrY2hIK090ZGZZbk9HeEJWb1BiTjRORlc1Y1lKU3JWempySkxmbHdZU1BBVnBvMzR6Z0l3Y2cxeEVmbW94YnYxc1YvNXZ4emJGL0IxNFp3&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-air-finish-select-202509-lightgold?wid=5120&hei=2880&fmt=webp&qlt=90&.v=NUpaQVl1bitSNmJWZUdKdi9QZHhsQnMyOXpiUEVyWXc0UFVFMUg1R1ZtcGFDdFMvVG1KZ1loaks5VzlLRGZIZkpFd0xhWDVibStLdGRYRmxkNGI4VTR2UjRaSC9URTlmd0FSb1ZTWjRnb3NmclJJZnl5SmNFYUJGS2w3dHkrT2M&traceId=1',
    ],
    soldCount: 289,
    rating: { score: 4.7, reviewsCount: 61 },
    price: { current: 109990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPhone',
    year: '2025',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '6.5"' },
          { name: 'Тип', value: 'Super Retina XDR OLED' },
          { name: 'Разрешение', value: '2740 × 1260 пикс.' },
          { name: 'Плотность пикселей', value: '460 пикс/дюйм' },
          { name: 'Частота обновления', value: '120 Гц (ProMotion)' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Always-On дисплей', value: 'Да' },
          { name: 'Dynamic Island', value: 'Да' },
          { name: 'Яркость', value: '1000 нит (典型), 1600 нит (HDR), 2000 нит (наружная)' },
          { name: 'Защитное стекло', value: 'Ceramic Shield (поколение 2)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A19 Pro' },
          { name: 'Ядра CPU', value: '6 (2 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '5' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '12 ГБ' },
          { name: 'Накопитель', value: '256 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '48 МП Fusion, ƒ/1.6' },
          { name: 'Видео', value: '4K 60 кадр/с, Dolby Vision' },
          { name: 'Оптический зум', value: '1×, 2×' },
          { name: 'Фронтальная', value: '18 МП Center Stage' },
          { name: 'Camera Control', value: 'Да' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '3 990 мАч' },
          { name: 'Автономность', value: 'до 27 ч (воспроизведение видео)' },
          { name: 'Быстрая зарядка', value: 'до 50% за 35 мин (адаптер 20 Вт)' },
          { name: 'Беспроводная зарядка', value: 'MagSafe 25 Вт, Qi2 15 Вт' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Light Gold' },
          { name: 'Материал корпуса', value: 'Титан' },
          { name: 'Безопасность', value: 'Face ID' },
          { name: 'ОС', value: 'iOS 19' },
          { name: 'Степень защиты', value: 'IP68' },
          { name: 'Action Button', value: 'Да' },
          { name: 'Толщина', value: '5.5 мм (самый тонкий iPhone)' },
          { name: 'Размеры', value: '158.1 × 76.0 × 5.5 мм' },
          { name: 'Вес', value: '165 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '22',
    title: 'Apple Pencil Pro',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MX2D3_AV2?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=YkR5TmNaZVZzVFlyQVNrVERHTzIvRlZya2lKWlJmUEwrYndWOTJiVWJWQUYwVmtIbGRkS25RMVpBRlo0bk5DUWh6K2ZUVlVERFk0Z2VkUHMxazl1aFE',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MX2D3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=aERwRkppV2pTZWx2MDU5ek9FWVpkd2tuVHYzMERCZURia3c5SzJFOTlPamtyK21QQVlqVGgrcGQ5Uy9BWWRGOUU5TjEzNDVxWGZyenF5K251RnVTZXc',
    ],
    soldCount: 320,
    rating: { score: 4.9, reviewsCount: 45 },
    price: { current: 14990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'Аксессуары',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Возможности',
        specs: [
          { name: 'Сенсорное управление', value: 'Да (сжатие, наклон)' },
          { name: 'Haptic Feedback', value: 'Да (отклик при сжатии)' },
          { name: 'Беспроводная зарядка', value: 'Магнитная (прикрепление к iPad)' },
          { name: 'Наклон', value: 'Определение наклона для рисования' },
          { name: 'Поворот', value: 'Определение вращения двойного конуса' },
        ],
      },
      {
        groupName: 'Совместимость',
        specs: [
          { name: 'iPad Pro', value: 'M4 и новее' },
          { name: 'iPad Air', value: 'M2 и новее' },
          { name: 'iPad mini', value: 'A17 Pro и новее' },
          { name: 'iPad', value: '10-го поколения и новее' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Подключение', value: 'Беспроводное (магнитное крепление)' },
          { name: 'Наконечник', value: 'Сменный (в комплекте)' },
          { name: 'Длина', value: '166 мм' },
          { name: 'Диаметр', value: '6.92 мм' },
          { name: 'Вес', value: '19.15 г' },
          { name: 'Цвет', value: 'White' },
        ],
      },
    ],
  },
  {
    id: '23',
    title: 'Apple iMac 24" M4 Silver',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/imac-specs-select-202601-silver-8-8-desktop_AV2?wid=5120&hei=3280&fmt=webp&qlt=90&.v=N2NZSkQ1R01LOENMUDBVSGZDQWUxRi9hdm1SVy9Yc3A0ZlQ0N21aN2E4dllRSHFlWnB0Sk9ndzVsMXl4WlF3UUVlNEJLYXlpcWN3dVUzSHNPQldJNDUyTGQvczVjTzVnd1B6UVQwaE1kY2dObXg1di9mYUU0N3k0WXY0TDh1SkRaOVRnSHJ3bjBJZGcvaGFFTitnRHB3&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/imac-specs-select-202601-silver-8-8-desktop_AV1?wid=5120&hei=3280&fmt=webp&qlt=90&.v=N2NZSkQ1R01LOENMUDBVSGZDQWUxRi9hdm1SVy9Yc3A0ZlQ0N21aN2E4dWEvYk94RVJVUWNidlRYdVhhNGErNUVlNEJLYXlpcWN3dVUzSHNPQldJNDUyTGQvczVjTzVnd1B6UVQwaE1kY2h5M0VSRzlDNW5MaDdoRktTR3FDT05FejA2NkhYT011SXg5OWpLTEFQdC9R&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/imac-specs-select-202601-silver-8-8-desktop?wid=5120&hei=3280&fmt=webp&qlt=90&.v=N2NZSkQ1R01LOENMUDBVSGZDQWUxRi9hdm1SVy9Yc3A0ZlQ0N21aN2E4c213RXJ5SHBGdFdsQTJxU3BOVmwrV0tZMGFKbG9yanhQdjZDS1dZUFFhRVE4bm1RcmlWRWp2eDN1WHNkSjNmUllVNnIwb3hqNktkUFFBOGlDUnhtVTc&traceId=1',
    ],
    soldCount: 112,
    rating: { score: 4.8, reviewsCount: 31 },
    price: { current: 139990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'Mac',
    year: '2024',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Дисплей',
        specs: [
          { name: 'Диагональ', value: '24"' },
          { name: 'Тип', value: '4.5K Retina' },
          { name: 'Разрешение', value: '4480 × 2520 пикс.' },
          { name: 'Плотность пикселей', value: '218 пикс/дюйм' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Яркость', value: '500 нит' },
          { name: 'Наностекло', value: 'Опционально (Nano-texture)' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple M4' },
          { name: 'Ядра CPU', value: '10 (4 производительных + 6 энергоэффективных)' },
          { name: 'Ядра GPU', value: '10' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '16 ГБ unified' },
          { name: 'Накопитель', value: '256 ГБ SSD' },
        ],
      },
      {
        groupName: 'Камера и звук',
        specs: [
          { name: 'Камера', value: '12 МП Center Stage' },
          { name: 'Динамики', value: 'Система шести динамиков с поддержкой Spatial Audio' },
          { name: 'Микрофоны', value: '3 студийных микрофона' },
        ],
      },
      {
        groupName: 'Порты',
        specs: [
          { name: 'Thunderbolt', value: '2 × Thunderbolt 4 (USB-C)' },
          { name: 'USB', value: '2 × USB-C (3.1 Gen 2)' },
          { name: 'Ethernet', value: '10/100/1000 Мбит/с' },
          { name: 'Аудио', value: '3.5 мм разъём для наушников' },
        ],
      },
      {
        groupName: 'Комплект',
        specs: [
          { name: 'Клавиатура', value: 'Magic Keyboard с Touch ID' },
          { name: 'Мышь', value: 'Magic Mouse' },
          { name: 'Питание', value: 'Кабель питания (магнитный)' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'Silver' },
          { name: 'Материал корпуса', value: '100% переработанный алюминий' },
          { name: 'ОС', value: 'macOS Sequoia' },
          { name: 'Веб-камера', value: '12 МП Center Stage' },
          { name: 'Размеры (дисплей)', value: '54.7 × 39.7 × 14.7 см' },
          { name: 'Вес', value: '4.44 кг' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
  {
    id: '24',
    title: 'Apple iPhone 17 128 ГБ White',
    images: [
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-finish-select-202509-white_AV2?wid=5120&hei=2880&fmt=webp&qlt=90&.v=WGdCRlQ0YVlqbTdXTEkxRnVQb0oxclZmSzgzdlhzQS95ekpRalhXU0JMVndldWhleFk2VHB6NDlUQUxjVzNPT09UVDVQbVhkcDIxQlRzeDZXVVpQSzYyL0ZSTzZrMWlpUU5CQlpuNHNUZytRVlZVSzhpZVVjZnU0cSs1cjFhcU8&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-finish-select-202509-white_AV1?wid=5120&hei=2880&fmt=webp&qlt=90&.v=WGdCRlQ0YVlqbTdXTEkxRnVQb0oxclZmSzgzdlhzQS95ekpRalhXU0JMVUZBajlBQXc5azFZVDNxU0FodEtxMk9UVDVQbVhkcDIxQlRzeDZXVVpQSzYyL0ZSTzZrMWlpUU5CQlpuNHNUZy9JYlJDRlVNRU1kQ0hDdVhIcW04ZXc&traceId=1',
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-finish-select-202509-white_GEO_US?wid=5120&hei=2880&fmt=webp&qlt=90&.v=WGdCRlQ0YVlqbTdXTEkxRnVQb0oxclZmSzgzdlhzQS95ekpRalhXU0JMVkRQR0pzaFhHemZ3ZzZNcDlHRHpJYnF2TWlpSzUzejRCZGt2SjJUNGl1VEE4bm1RcmlWRWp2eDN1WHNkSjNmUmFBdlBzZ01jTzlOOGhYc3dpcENYM2Y&traceId=1',
    ],
    soldCount: 478,
    rating: { score: 4.6, reviewsCount: 112 },
    price: { current: 79990 },
    availability: ProductAvailability.IN_STOCK,
    category: 'iPhone',
    year: '2025',
    warrantyPeriod: 'Гарантия 1 год',
    specifications: [
      {
        groupName: 'Экран',
        specs: [
          { name: 'Диагональ', value: '6.3"' },
          { name: 'Тип', value: 'Super Retina XDR OLED' },
          { name: 'Разрешение', value: '2622 × 1206 пикс.' },
          { name: 'Плотность пикселей', value: '460 пикс/дюйм' },
          { name: 'Частота обновления', value: '120 Гц (ProMotion)' },
          { name: 'Палитра', value: 'P3 широкий цвет' },
          { name: 'True Tone', value: 'Да' },
          { name: 'Always-On дисплей', value: 'Да' },
          { name: 'Dynamic Island', value: 'Да' },
          { name: 'Яркость', value: '1000 нит (典型), 1600 нит (HDR), 2000 нит (наружная)' },
          { name: 'Защитное стекло', value: 'Ceramic Shield' },
        ],
      },
      {
        groupName: 'Производительность',
        specs: [
          { name: 'Процессор', value: 'Apple A19' },
          { name: 'Ядра CPU', value: '6 (2 производительных + 4 энергоэффективных)' },
          { name: 'Ядра GPU', value: '5' },
          { name: 'Neural Engine', value: '16-ядерный' },
          { name: 'Оперативная память', value: '8 ГБ' },
          { name: 'Накопитель', value: '128 ГБ' },
        ],
      },
      {
        groupName: 'Камера',
        specs: [
          { name: 'Основная', value: '48 МП Dual Fusion, ƒ/1.6' },
          { name: 'Сверхширокоугольная', value: '48 МП Ultra Wide, ƒ/2.2' },
          { name: 'Видео', value: '4K 60 кадр/с, Dolby Vision' },
          { name: 'Оптический зум', value: '0.5×, 1×, 2×' },
          { name: 'Фронтальная', value: '18 МП Center Stage' },
          { name: 'Macro', value: 'Да' },
        ],
      },
      {
        groupName: 'Аккумулятор и зарядка',
        specs: [
          { name: 'Ёмкость', value: '3 561 мАч' },
          { name: 'Автономность', value: 'до 30 ч (воспроизведение видео)' },
          { name: 'Быстрая зарядка', value: 'до 50% за 35 мин (адаптер 20 Вт)' },
          { name: 'Беспроводная зарядка', value: 'MagSafe 25 Вт, Qi2 15 Вт' },
        ],
      },
      {
        groupName: 'Общие характеристики',
        specs: [
          { name: 'Цвет', value: 'White' },
          { name: 'Материал корпуса', value: 'Алюминий (цельный)' },
          { name: 'Безопасность', value: 'Face ID' },
          { name: 'ОС', value: 'iOS 19' },
          { name: 'Степень защиты', value: 'IP68' },
          { name: 'Action Button', value: 'Да' },
          { name: 'Camera Control', value: 'Да' },
          { name: 'Размеры', value: '146.9 × 71.5 × 7.8 мм' },
          { name: 'Вес', value: '170 г' },
          { name: 'Страна производитель', value: 'Китай' },
        ],
      },
    ],
  },
]
